services:
  default_postgres:
    container_name: default_postgres
    image: postgres:13.5
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - "$DB_PORT:5432"
