CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role INT DEFAULT 1 CHECK (role IN (0, 1)),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);